// <auto-generated />
using System;
using Infrastructure.Persistence.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241020134142_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:CollationDefinition:case_insensitive", "en-u-ks-primary,en-u-ks-primary,icu,False")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ChandaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ChandaTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("chanda_type_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("InvoiceItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_item_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modified_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.HasKey("Id");

                    b.HasIndex("ChandaTypeId");

                    b.HasIndex("InvoiceItemId");

                    b.ToTable("chanda_items", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ChandaType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code")
                        .UseCollation("case_insensitive");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .UseCollation("case_insensitive");

                    b.Property<Guid>("IncomeAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("income_account_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modified_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("chanda_type", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Circuit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modified_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("circuits", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("JamaatId")
                        .HasColumnType("uuid")
                        .HasColumnName("jamaat_id");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modified_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference")
                        .UseCollation("case_insensitive");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("JamaatId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.InvoiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("JamaatId")
                        .HasColumnType("uuid")
                        .HasColumnName("jamaat_id");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modified_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("MonthPaidFor")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("month_paid_for");

                    b.Property<Guid>("PayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("payer_id");

                    b.Property<string>("ReceiptNo")
                        .HasColumnType("text")
                        .HasColumnName("receipt_no")
                        .UseCollation("case_insensitive");

                    b.Property<string>("ReferenceNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference_no")
                        .UseCollation("case_insensitive");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("JamaatId");

                    b.HasIndex("PayerId");

                    b.HasIndex("ReceiptNo")
                        .IsUnique();

                    b.ToTable("invoice_items", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Jamaat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CircuitId")
                        .HasColumnType("uuid")
                        .HasColumnName("circuit_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JamaatLedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("jamaat_ledger_id");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modified_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex("CircuitId");

                    b.ToTable("jamaats", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.JamaatLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JamaatId")
                        .HasColumnType("uuid")
                        .HasColumnName("jamaat_id");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modified_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.HasKey("Id");

                    b.HasIndex("JamaatId")
                        .IsUnique();

                    b.ToTable("jamaat_ledgers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Ledger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ChandaTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("chanda_type_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entry_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("JamaatLedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("jamaat_ledger_id");

                    b.Property<Guid?>("MemberLedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_ledger_id");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modified_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("MonthPaidFor")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("month_paid_for");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("ChandaTypeId");

                    b.HasIndex("JamaatLedgerId");

                    b.HasIndex("MemberLedgerId");

                    b.ToTable("ledgers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChandaNo")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("chanda_no")
                        .UseCollation("case_insensitive");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email")
                        .UseCollation("case_insensitive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JamaatId")
                        .HasColumnType("uuid")
                        .HasColumnName("jamaat_id");

                    b.Property<Guid>("MemberLedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_ledger_id");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modified_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name")
                        .UseCollation("case_insensitive");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone_no")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex("ChandaNo")
                        .IsUnique();

                    b.HasIndex("JamaatId");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.MemberLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modified_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("member_ledgers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.MemberRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modified_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("role_name")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("RoleId");

                    b.ToTable("member_roles", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("amount");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modified_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("option");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference")
                        .UseCollation("case_insensitive");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cron_expression")
                        .UseCollation("case_insensitive");

                    b.Property<int>("Day")
                        .HasColumnType("integer")
                        .HasColumnName("day");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description")
                        .UseCollation("case_insensitive");

                    b.Property<int>("Hour")
                        .HasColumnType("integer")
                        .HasColumnName("hour");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<int>("Minute")
                        .HasColumnType("integer")
                        .HasColumnName("minute");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReminderTitle")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("reminder_title")
                        .UseCollation("case_insensitive");

                    b.Property<bool>("ViaMail")
                        .HasColumnType("boolean")
                        .HasColumnName("via_mail");

                    b.Property<bool>("ViaSMS")
                        .HasColumnType("boolean")
                        .HasColumnName("via_sms");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("reminders", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description")
                        .UseCollation("case_insensitive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fc384e77-9456-4176-b3f8-aa7b5043dcb5"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2024, 1, 1, 3, 10, 28, 488, DateTimeKind.Utc),
                            Description = "Full administrative access across the system.",
                            IsDeleted = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("27d159c7-310a-449d-ab22-a3bcf2f3e585"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2024, 1, 1, 3, 10, 28, 488, DateTimeKind.Utc),
                            Description = "Head of AMJN",
                            IsDeleted = false,
                            Name = "Amir"
                        },
                        new
                        {
                            Id = new Guid("54e5e167-1ce3-49a7-b372-76e31af6326c"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2024, 1, 1, 3, 10, 28, 488, DateTimeKind.Utc),
                            Description = "Acting Head of AMJN",
                            IsDeleted = false,
                            Name = "Acting-Amir"
                        },
                        new
                        {
                            Id = new Guid("fe8e4f67-6212-47b7-bb90-b6fbf52c0ef0"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2024, 1, 1, 3, 10, 28, 488, DateTimeKind.Utc),
                            Description = "Naib Amir",
                            IsDeleted = false,
                            Name = "Naib-Amir"
                        },
                        new
                        {
                            Id = new Guid("b19f4a12-5fcb-408f-9b81-e7001fc0d0bf"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2024, 1, 1, 3, 10, 28, 488, DateTimeKind.Utc),
                            Description = "National General Secretary.",
                            IsDeleted = false,
                            Name = "Nationa-Gen-Sec"
                        },
                        new
                        {
                            Id = new Guid("63f17b42-e04f-44ff-a38e-d0808125a45f"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2024, 1, 1, 3, 10, 28, 488, DateTimeKind.Utc),
                            Description = "National Financial Secretary",
                            IsDeleted = false,
                            Name = "National-Fin-Sec"
                        },
                        new
                        {
                            Id = new Guid("da2712fa-6181-4f4c-a572-db014eac3dc3"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2024, 1, 1, 3, 10, 28, 488, DateTimeKind.Utc),
                            Description = "National Tajneed Secretary",
                            IsDeleted = false,
                            Name = "National-Tajneed"
                        },
                        new
                        {
                            Id = new Guid("cbaf21ea-a91f-4e41-b89e-521ce5cc0d4b"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2024, 1, 1, 3, 10, 28, 488, DateTimeKind.Utc),
                            Description = "Circuit President.",
                            IsDeleted = false,
                            Name = "CP"
                        },
                        new
                        {
                            Id = new Guid("9810b39a-3a25-4204-aee7-bb093df6f13a"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2024, 1, 1, 3, 10, 28, 488, DateTimeKind.Utc),
                            Description = "Vice Circuit President.",
                            IsDeleted = false,
                            Name = "VCP"
                        },
                        new
                        {
                            Id = new Guid("99f78295-f3c2-417b-a2b0-d9e9eedc7210"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2024, 1, 1, 3, 10, 28, 488, DateTimeKind.Utc),
                            Description = "Circuit Financial Secretary.",
                            IsDeleted = false,
                            Name = "Circuit-Fin-Sec"
                        },
                        new
                        {
                            Id = new Guid("9ff7d3e5-e32b-4528-8a4d-eaa57a561c33"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2024, 1, 1, 3, 10, 28, 488, DateTimeKind.Utc),
                            Description = "Jamaat Financial Secretary.",
                            IsDeleted = false,
                            Name = "Jamaat-Fin-Sec"
                        },
                        new
                        {
                            Id = new Guid("2100e19d-699a-4ce2-be0b-ac7f56cc59d2"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2024, 1, 1, 3, 10, 28, 488, DateTimeKind.Utc),
                            Description = "Jamaat President.",
                            IsDeleted = false,
                            Name = "Jamaat-President"
                        },
                        new
                        {
                            Id = new Guid("d38c87ba-e03c-4844-a590-cef509a992b0"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2024, 1, 1, 3, 10, 28, 488, DateTimeKind.Utc),
                            Description = "Circuit General Secretary.",
                            IsDeleted = false,
                            Name = "Circuit-Gen-Sec"
                        },
                        new
                        {
                            Id = new Guid("67e91d08-6237-49a1-98f4-b18ddf693520"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2024, 1, 1, 3, 10, 28, 488, DateTimeKind.Utc),
                            Description = "Jamaat General Secretary.",
                            IsDeleted = false,
                            Name = "Jamaat-Gen-Sec"
                        },
                        new
                        {
                            Id = new Guid("a8e40cba-51c9-45de-83c8-3e1d1fb415d7"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2024, 1, 1, 3, 10, 28, 488, DateTimeKind.Utc),
                            Description = "Jamaat Member.",
                            IsDeleted = false,
                            Name = "Member"
                        });
                });

            modelBuilder.Entity("Infrastructure.Middleware.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("Domain.Entities.ChandaItem", b =>
                {
                    b.HasOne("Domain.Entities.ChandaType", "ChandaType")
                        .WithMany()
                        .HasForeignKey("ChandaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.InvoiceItem", "InvoiceItem")
                        .WithMany("ChandaItems")
                        .HasForeignKey("InvoiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChandaType");

                    b.Navigation("InvoiceItem");
                });

            modelBuilder.Entity("Domain.Entities.Invoice", b =>
                {
                    b.HasOne("Domain.Entities.Jamaat", "Jamaat")
                        .WithMany()
                        .HasForeignKey("JamaatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jamaat");
                });

            modelBuilder.Entity("Domain.Entities.InvoiceItem", b =>
                {
                    b.HasOne("Domain.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Jamaat", "Jamaat")
                        .WithMany()
                        .HasForeignKey("JamaatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Jamaat");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Domain.Entities.Jamaat", b =>
                {
                    b.HasOne("Domain.Entities.Circuit", "Circuit")
                        .WithMany("Jamaats")
                        .HasForeignKey("CircuitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Circuit");
                });

            modelBuilder.Entity("Domain.Entities.JamaatLedger", b =>
                {
                    b.HasOne("Domain.Entities.Jamaat", "Jamaat")
                        .WithOne("JamaatLedger")
                        .HasForeignKey("Domain.Entities.JamaatLedger", "JamaatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Jamaat");
                });

            modelBuilder.Entity("Domain.Entities.Ledger", b =>
                {
                    b.HasOne("Domain.Entities.ChandaType", "ChandaType")
                        .WithMany()
                        .HasForeignKey("ChandaTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.JamaatLedger", "JamaatLedger")
                        .WithMany("LedgerList")
                        .HasForeignKey("JamaatLedgerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.MemberLedger", "MemberLedger")
                        .WithMany("LedgerList")
                        .HasForeignKey("MemberLedgerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChandaType");

                    b.Navigation("JamaatLedger");

                    b.Navigation("MemberLedger");
                });

            modelBuilder.Entity("Domain.Entities.Member", b =>
                {
                    b.HasOne("Domain.Entities.Jamaat", "Jamaat")
                        .WithMany("Members")
                        .HasForeignKey("JamaatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Jamaat");
                });

            modelBuilder.Entity("Domain.Entities.MemberLedger", b =>
                {
                    b.HasOne("Domain.Entities.Member", "Member")
                        .WithOne("MemberLedger")
                        .HasForeignKey("Domain.Entities.MemberLedger", "MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Domain.Entities.MemberRole", b =>
                {
                    b.HasOne("Domain.Entities.Member", "Member")
                        .WithMany("MemberRoles")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("MemberRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.HasOne("Domain.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Domain.Entities.Reminder", b =>
                {
                    b.HasOne("Domain.Entities.Member", "Member")
                        .WithMany("Reminders")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Domain.Entities.Circuit", b =>
                {
                    b.Navigation("Jamaats");
                });

            modelBuilder.Entity("Domain.Entities.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Domain.Entities.InvoiceItem", b =>
                {
                    b.Navigation("ChandaItems");
                });

            modelBuilder.Entity("Domain.Entities.Jamaat", b =>
                {
                    b.Navigation("JamaatLedger")
                        .IsRequired();

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Domain.Entities.JamaatLedger", b =>
                {
                    b.Navigation("LedgerList");
                });

            modelBuilder.Entity("Domain.Entities.Member", b =>
                {
                    b.Navigation("MemberLedger")
                        .IsRequired();

                    b.Navigation("MemberRoles");

                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("Domain.Entities.MemberLedger", b =>
                {
                    b.Navigation("LedgerList");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("MemberRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
