// <auto-generated />
using System;
using Infrastructure.Persistence.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:CollationDefinition:case_insensitive", "en-u-ks-primary,en-u-ks-primary,icu,False")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ChandaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ChandaTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("chanda_type_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("InvoiceItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_item_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modified_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.HasKey("Id");

                    b.HasIndex("ChandaTypeId");

                    b.HasIndex("InvoiceItemId");

                    b.ToTable("chanda_items", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ChandaType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("code")
                        .UseCollation("case_insensitive");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .UseCollation("case_insensitive");

                    b.Property<Guid>("IncomeAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("income_account_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modified_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("chanda_type", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Circuit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modified_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("circuits", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("JamaatId")
                        .HasColumnType("uuid")
                        .HasColumnName("jamaat_id");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modified_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("JamaatId");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.InvoiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modified_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("MonthPaidFor")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("month_paid_for")
                        .UseCollation("case_insensitive");

                    b.Property<Guid>("PayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("payer_id");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PayerId");

                    b.ToTable("invoice_items", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Jamaat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CircuitId")
                        .HasColumnType("uuid")
                        .HasColumnName("circuit_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modified_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex("CircuitId");

                    b.ToTable("jamaats", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.JamaatLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JamaatId")
                        .HasColumnType("uuid")
                        .HasColumnName("jamaat_id");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modified_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.HasKey("Id");

                    b.HasIndex("JamaatId");

                    b.ToTable("jamaat_ledgers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Ledger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ChandaTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("chanda_type_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entry_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("JamaatLedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("jamaat_ledger_id");

                    b.Property<Guid?>("MemberLedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_ledger_id");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modified_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("MonthPaidFor")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("month_paid_for")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex("ChandaTypeId");

                    b.HasIndex("JamaatLedgerId");

                    b.HasIndex("MemberLedgerId");

                    b.ToTable("ledgers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChandaNo")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("chanda_no")
                        .UseCollation("case_insensitive");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email")
                        .UseCollation("case_insensitive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JamaatId")
                        .HasColumnType("uuid")
                        .HasColumnName("jamaat_id");

                    b.Property<Guid>("MemberLedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_ledger_id");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modified_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name")
                        .UseCollation("case_insensitive");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone_no")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex("ChandaNo")
                        .IsUnique();

                    b.HasIndex("JamaatId");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.MemberLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modified_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("member_ledgers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.MemberRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modified_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("RoleId");

                    b.ToTable("member_roles", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("amount");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modified_by")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("option");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description")
                        .UseCollation("case_insensitive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .UseCollation("case_insensitive");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2ab3146b-b006-4556-b511-489ae61fbb36"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2023, 10, 30, 2, 10, 28, 488, DateTimeKind.Utc),
                            Description = "Full administrative access across the system.",
                            IsDeleted = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("c721467c-11ab-4345-8bf5-69903eababad"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2023, 10, 30, 2, 10, 28, 488, DateTimeKind.Utc),
                            Description = "Head of AMJN",
                            IsDeleted = false,
                            Name = "Amir"
                        },
                        new
                        {
                            Id = new Guid("2ba5f679-4f0d-49d2-946e-d8b1a56f0c63"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2023, 10, 30, 2, 10, 28, 488, DateTimeKind.Utc),
                            Description = "Acting Head of AMJN",
                            IsDeleted = false,
                            Name = "Acting-Amir"
                        },
                        new
                        {
                            Id = new Guid("8b010dc8-4617-4aaa-8e9c-25d15c813171"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2023, 10, 30, 2, 10, 28, 488, DateTimeKind.Utc),
                            Description = "Naib Amir",
                            IsDeleted = false,
                            Name = "Naib-Amir"
                        },
                        new
                        {
                            Id = new Guid("53167742-b6df-44f2-94b4-3c8f70b2bc0f"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2023, 10, 30, 2, 10, 28, 488, DateTimeKind.Utc),
                            Description = "National General Secretary.",
                            IsDeleted = false,
                            Name = "Nationa-Gen-Sec"
                        },
                        new
                        {
                            Id = new Guid("c0e1e9ef-9cd0-429b-a8fb-ecf4261165b6"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2023, 10, 30, 2, 10, 28, 488, DateTimeKind.Utc),
                            Description = "National Financial Secretary",
                            IsDeleted = false,
                            Name = "National-Fin-Sec"
                        },
                        new
                        {
                            Id = new Guid("e951f38e-9a94-4fa6-bb65-99aa40d4917e"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2023, 10, 30, 2, 10, 28, 488, DateTimeKind.Utc),
                            Description = "National Tajneed Secretary",
                            IsDeleted = false,
                            Name = "National-Tajneed"
                        },
                        new
                        {
                            Id = new Guid("ba2754fe-32be-4b8d-8965-75eae25d6c5d"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2023, 10, 30, 2, 10, 28, 488, DateTimeKind.Utc),
                            Description = "Circuit President.",
                            IsDeleted = false,
                            Name = "CP"
                        },
                        new
                        {
                            Id = new Guid("39edd755-1045-42ec-9bff-4eab330761f6"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2023, 10, 30, 2, 10, 28, 488, DateTimeKind.Utc),
                            Description = "Vice Circuit President.",
                            IsDeleted = false,
                            Name = "VCP"
                        },
                        new
                        {
                            Id = new Guid("ca90b66b-893a-49e7-a87f-ec67b13c8ab7"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2023, 10, 30, 2, 10, 28, 488, DateTimeKind.Utc),
                            Description = "Circuit Financial Secretary.",
                            IsDeleted = false,
                            Name = "Circuit-Fin-Sec"
                        },
                        new
                        {
                            Id = new Guid("70c7596e-eed4-4fe0-9d56-12e5e4a8c1d2"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2023, 10, 30, 2, 10, 28, 488, DateTimeKind.Utc),
                            Description = "Jamaat Financial Secretary.",
                            IsDeleted = false,
                            Name = "Jamaat-Fin-Sec"
                        },
                        new
                        {
                            Id = new Guid("148e1dae-fd66-4175-9d5e-4586820452e1"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2023, 10, 30, 2, 10, 28, 488, DateTimeKind.Utc),
                            Description = "Jamaat President.",
                            IsDeleted = false,
                            Name = "Jamaat-President"
                        },
                        new
                        {
                            Id = new Guid("2b0ee60c-aa73-40c9-b876-0fbdab84755c"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2023, 10, 30, 2, 10, 28, 488, DateTimeKind.Utc),
                            Description = "Circuit General Secretary.",
                            IsDeleted = false,
                            Name = "Circuit-Gen-Sec"
                        },
                        new
                        {
                            Id = new Guid("09db637a-07ea-4488-a78b-a2f52ec0d1cd"),
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2023, 10, 30, 2, 10, 28, 488, DateTimeKind.Utc),
                            Description = "Jamaat General Secretary.",
                            IsDeleted = false,
                            Name = "Jamaat-Gen-Sec"
                        });
                });

            modelBuilder.Entity("Domain.Entities.ChandaItem", b =>
                {
                    b.HasOne("Domain.Entities.ChandaType", "ChandaType")
                        .WithMany()
                        .HasForeignKey("ChandaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.InvoiceItem", "InvoiceItem")
                        .WithMany("ChandaItems")
                        .HasForeignKey("InvoiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChandaType");

                    b.Navigation("InvoiceItem");
                });

            modelBuilder.Entity("Domain.Entities.Invoice", b =>
                {
                    b.HasOne("Domain.Entities.Jamaat", "Jamaat")
                        .WithMany()
                        .HasForeignKey("JamaatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jamaat");
                });

            modelBuilder.Entity("Domain.Entities.InvoiceItem", b =>
                {
                    b.HasOne("Domain.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Domain.Entities.Jamaat", b =>
                {
                    b.HasOne("Domain.Entities.Circuit", "Circuit")
                        .WithMany("Jamaats")
                        .HasForeignKey("CircuitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Circuit");
                });

            modelBuilder.Entity("Domain.Entities.JamaatLedger", b =>
                {
                    b.HasOne("Domain.Entities.Jamaat", "Jamaat")
                        .WithMany()
                        .HasForeignKey("JamaatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jamaat");
                });

            modelBuilder.Entity("Domain.Entities.Ledger", b =>
                {
                    b.HasOne("Domain.Entities.ChandaType", "ChandaType")
                        .WithMany()
                        .HasForeignKey("ChandaTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.JamaatLedger", "JamaatLedger")
                        .WithMany("LedgerList")
                        .HasForeignKey("JamaatLedgerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.MemberLedger", "MemberLedger")
                        .WithMany("LedgerList")
                        .HasForeignKey("MemberLedgerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChandaType");

                    b.Navigation("JamaatLedger");

                    b.Navigation("MemberLedger");
                });

            modelBuilder.Entity("Domain.Entities.Member", b =>
                {
                    b.HasOne("Domain.Entities.Jamaat", "Jamaat")
                        .WithMany("Members")
                        .HasForeignKey("JamaatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Jamaat");
                });

            modelBuilder.Entity("Domain.Entities.MemberLedger", b =>
                {
                    b.HasOne("Domain.Entities.Member", "Member")
                        .WithOne("MemberLedger")
                        .HasForeignKey("Domain.Entities.MemberLedger", "MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Domain.Entities.MemberRole", b =>
                {
                    b.HasOne("Domain.Entities.Member", "Member")
                        .WithMany("MemberRoles")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("MemberRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.HasOne("Domain.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Domain.Entities.Circuit", b =>
                {
                    b.Navigation("Jamaats");
                });

            modelBuilder.Entity("Domain.Entities.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Domain.Entities.InvoiceItem", b =>
                {
                    b.Navigation("ChandaItems");
                });

            modelBuilder.Entity("Domain.Entities.Jamaat", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Domain.Entities.JamaatLedger", b =>
                {
                    b.Navigation("LedgerList");
                });

            modelBuilder.Entity("Domain.Entities.Member", b =>
                {
                    b.Navigation("MemberLedger")
                        .IsRequired();

                    b.Navigation("MemberRoles");
                });

            modelBuilder.Entity("Domain.Entities.MemberLedger", b =>
                {
                    b.Navigation("LedgerList");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("MemberRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
